### ISSUE TITLE
Make session title at card scrollable

### ISSUE THREAD

**Issue by leonardoxh** [leonardoxh/race-control-tv#24]
When the title is to big, the card title should be scrollable automatically so we can read everything

**Comment by j0bro** [comment]
Was about to file an issue since the awesome 2.0 update, but it seems it's already on your radar! Apparently you added some prefixes to the card titles which shift the important bit of the title out of sight.
Don't know if scrolling will lead to a pleasant UI, maybe the use of wider cards can help since the available screen real estate easily allows for it.

**Comment by schumi2004** [comment]
Word wrap in multiple lines over the thumbnail image?

**Comment by leonardoxh** [comment]
"Apparently you added some prefixes to the card titles" <- There is no prefixes :D The names on the 2.0 APIS are slight bigger, and the paddings on the card are not really customisable on Leanback.

Increase the card w/h could be a possibility, but it is not guaranteed that will work all the time :D But I think for UI is what makes more sense at moment

**Comment by schumi2004** [comment]
Can the card height be adjusted and use word wrap?

**Comment by leonardoxh** [comment]
on leanback I have to set the width and height

**Comment by leonardoxh** [comment]
However making it 2 lines doesn't look so ugly and is a quick and easy fix:

<img width="689" alt="Screenshot 2021-03-18 at 17 03 38" src="https://user-images.githubusercontent.com/1267788/111657608-e3a21480-880b-11eb-8f22-f62d0e50060c.png">
