### ISSUE TITLE
App not available in playstore

### ISSUE THREAD

**Issue by anton264** [leonardoxh/race-control-tv#6]
Using a Nvidia shield (older model) when I open the link to the play store it says not available for any devices. When searching on the shield itself I can not seem to find it. I cloned and build the app myself and side loaded to the shield which seems to work just fine so it is weird why it does not work through the play store.

**Comment by j0bro** [comment]
I have the same issue, we probably have to wait a bit. @leonardoxh just checking, did you publish it with public visibility?

**Comment by leonardoxh** [comment]
Hm my bet is that I did not release for the country you live (I released it to 35 countries only) mainly in Europe.

I can release it to the country you guys live, just let me know what is it

**Comment by j0bro** [comment]
Netherlands, thanks in advance!

**Comment by leonardoxh** [comment]
I added a few more countries to the list right now, including Belgium, I live in the netherlands as well, maybe now it goes, otherwise can be that it is not available for your device, on Playstore I see 500+ devices available, then maybe we have to add it manually

**Comment by j0bro** [comment]
I have a Philips 65OLED804 tv running Android TV 9.0, the model is TPM191E. Let me know if you need more info. I could compile the APK myself, or even publish it but I thought I'd help you out since you already have it on the Play Store.

**Comment by anton264** [comment]
I am in Sweden, upon trying again this morning I can now install the app. Thank you!

**Comment by leonardoxh** [comment]
@j0bro I believe you can try again ?

**Comment by j0bro** [comment]
I did, you could not find the app in the TV's Google Play search results (yet). However, logging in the Play Store via my laptop and installing it on the TV from there worked. So compatibility is OK, but maybe it takes a while still to pop up in the TV's Google Play app? App seems to function 100% btw. Some usability improvements could be to make the highlight of the selected OSD button somewhat more contrast-y and to allow for skipping through a replay using the progress bar. Otherwise, excellent job!

**Comment by leonardoxh** [comment]
Yeah, for me the main pain point of the app is the code itself. For me it doesn't use the View models properly, so I believe I will start to refactor these parts soon
